version: "3.9"

services:
  posgresql:
    hostname: postgresql
    container_name: postgresql
    build: ./my-postgres
    restart: always
    environment:
      POSTGRES_DB: CollectEats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./my-postgres/CollectEats.sql:/docker-entrypoint-initdb.d/CollectEats.sql
    ports:
      - "5432:5432"
  angular:
    hostname: angular
    container_name: angular
    build: ./PoCCollectEats
    ports:
      - 4200:4200
  net:
    hostname: net
    container_name: net
    build: ./CollectEats
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7242:80"
      - "5113:5113"
  keycloak:
    build: ./keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/keycloak-conf.json:/opt/keycloak/conf/keycloak-conf.json
    ports:
      - 8080:8080
